# Generated by Django 3.0.3 on 2022-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='task',
            name='phone',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
